### ISSUE TITLE
nevver assume

### ISSUE THREAD

**Issue by tschallacka** [fingersome/fingersome.dorfcraft#1]
player.getHeldItem().getItem() =

Dont just check null.
Also check stacksize. Print out the getheld item to see what it contains with empty hand

For the sound, you could add a tileentity that stores last tick when sound was played. Then only activate sound if 20 ticks have passed sincelast tick. You need to sibscribe to server tick event to increase your cpunter

**Comment by tschallacka** [comment]
Excuse my horrible typing

**Comment by fingersome** [comment]
no worries, thanks for the pointers dude c:
